exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('repos').del()
    .then(function () {
      // Inserts seed entries
      return knex('repos').insert([
        { id: 1, repo_name: 'dog-tinder', repo_link: 'https://github.com/aihe-2020/dog-tinder' },
        { id: 2, repo_name: 'day-tripper', repo_link: 'https://github.com/aihe-2020/day-tripper' },
        { id: 3, repo_name: 'aihe-book', repo_link: 'https://github.com/aihe-2020/aihe-book' },
        { id: 4, repo_name: 'jv-jokes', repo_link: 'https://github.com/aihe-2020/jv-jokes' },
        { id: 5, repo_name: 'boilerplate-fullstack', repo_link: 'https://github.com/aihe-2020/boilerplate-fullstack' },
        { id: 6, repo_name: 'todo-full-stack', repo_link: 'https://github.com/aihe-2020/todo-full-stack' },
        { id: 7, repo_name: 'knex-joins-stories', repo_link: 'https://github.com/aihe-2020/knex-joins-stories' },
        { id: 8, repo_name: 'pupparazzi', repo_link: 'https://github.com/aihe-2020/pupparazzi' },
        { id: 9, repo_name: 'jwt-auth', repo_link: 'https://github.com/aihe-2020/jwt-auth' },
        { id: 10, repo_name: 'charlottes-web-log-api', repo_link: 'https://github.com/aihe-2020/charlottes-web-log-api' },
        { id: 11, repo_name: 'GitLit', repo_link: 'https://github.com/aihe-2020/GitLit' },
        { id: 12, repo_name: 'TheButton', repo_link: 'https://github.com/aihe-2020/TheButton' },
        { id: 13, repo_name: 'code-from-class', repo_link: 'https://github.com/aihe-2020/code-from-class' },
        { id: 14, repo_name: 'React-App-Project', repo_link: 'https://github.com/aihe-2020/React-App-Project' },
        { id: 15, repo_name: 'async-redux-stories', repo_link: 'https://github.com/aihe-2020/async-redux-stories' },
        { id: 16, repo_name: 'taxonomic-routing', repo_link: 'https://github.com/aihe-2020/taxonomic-routing' },
        { id: 17, repo_name: 'sweet-as-beers', repo_link: 'https://github.com/aihe-2020/sweet-as-beers' },
        { id: 18, repo_name: 'boilerplate-react-webpack', repo_link: 'https://github.com/aihe-2020/boilerplate-react-webpack' },
        { id: 19, repo_name: 'react-redux-stories', repo_link: 'https://github.com/aihe-2020/react-redux-stories' },
        { id: 20, repo_name: 'lightning-talks', repo_link: 'https://github.com/aihe-2020/lightning-talks' },
        { id: 21, repo_name: 'redux-minimal', repo_link: 'https://github.com/aihe-2020/redux-minimal' },
        { id: 22, repo_name: 'broken-kaleidoscope', repo_link: 'https://github.com/aihe-2020/broken-kaleidoscope' },
        { id: 23, repo_name: 'donbot', repo_link: 'https://github.com/aihe-2020/donbot' },
        { id: 24, repo_name: 'surrendedAt13', repo_link: 'https://github.com/aihe-2020/surrendedAt13' },
        { id: 25, repo_name: 'You-Are-Fired', repo_link: 'https://github.com/aihe-2020/You-Are-Fired' },
        { id: 26, repo_name: 'meme-generator', repo_link: 'https://github.com/aihe-2020/meme-generator' },
        { id: 27, repo_name: 'consuming-external-apis', repo_link: 'https://github.com/aihe-2020/consuming-external-apis' },
        { id: 28, repo_name: 'knex-todo-cli', repo_link: 'https://github.com/aihe-2020/knex-todo-cli' },
        { id: 29, repo_name: 'Banksies-untiled-2020-project', repo_link: 'https://github.com/aihe-2020/Banksies-untiled-2020-project' },
        { id: 30, repo_name: 'soundboard-senpai', repo_link: 'https://github.com/aihe-2020/soundboard-senpai' },
        { id: 31, repo_name: 'cursed-cursor', repo_link: 'https://github.com/aihe-2020/cursed-cursor' },
        { id: 32, repo_name: 'knex-relationships-stories', repo_link: 'https://github.com/aihe-2020/knex-relationships-stories' },
        { id: 33, repo_name: 'react-form-demo', repo_link: 'https://github.com/aihe-2020/eact-form-demo' },
        { id: 34, repo_name: 'ascii-art-reader', repo_link: 'https://github.com/aihe-2020/ascii-art-reader' },
        { id: 35, repo_name: 'totally-legal-pokedex', repo_link: 'https://github.com/aihe-2020/totally-legal-pokedex' },
        { id: 36, repo_name: 'memory', repo_link: 'https://github.com/aihe-2020/memory' },
        { id: 37, repo_name: 'NZ-Cities-Cardgame', repo_link: 'https://github.com/aihe-2020/NZ-Cities-Cardgame' },
        { id: 38, repo_name: 'react-paws-for-effect', repo_link: 'https://github.com/aihe-2020/react-paws-for-effect' },
        { id: 39, repo_name: 'server-side-rendering', repo_link: 'https://github.com/aihe-2020/server-side-rendering' },
        { id: 40, repo_name: 'conways', repo_link: 'https://github.com/aihe-2020/conways' },
        { id: 41, repo_name: 'express-server', repo_link: 'https://github.com/aihe-2020/express-server' },
        { id: 42, repo_name: 'bowling-kata', repo_link: 'https://github.com/aihe-2020/bowling-kata' },
        { id: 43, repo_name: 'knex-forms-stories', repo_link: 'https://github.com/aihe-2020/knex-forms-stories' },
        { id: 44, repo_name: 'Devurban-dictionary', repo_link: 'https://github.com/aihe-2020/Devurban-dictionary' },
        { id: 45, repo_name: 'boilerplate-knex', repo_link: 'https://github.com/aihe-2020/boilerplate-knex' },
        { id: 46, repo_name: 'Sporkman-and-friends-', repo_link: 'https://github.com/aihe-2020/Sporkman-and-friends-' },
        { id: 47, repo_name: 'STEW-GEN', repo_link: 'https://github.com/aihe-2020/STEW-GEN' },
        { id: 48, repo_name: 'tdd-bowling-kata', repo_link: 'https://github.com/aihe-2020/tdd-bowling-kata' },
        { id: 49, repo_name: 'kata-data-structures', repo_link: 'https://github.com/aihe-2020/kata-data-structures' },
        { id: 50, repo_name: 'two-truths-and-a-lie', repo_link: 'https://github.com/aihe-2020/two-truths-and-a-lie' },
        { id: 51, repo_name: 'kata-types-modules', repo_link: 'https://github.com/aihe-2020/kata-types-modules' },
        { id: 52, repo_name: 'kata-strings-numbers-modules', repo_link: 'https://github.com/aihe-2020/kata-strings-numbers-modules' },
        { id: 53, repo_name: 'kata-objects-and-arrays', repo_link: 'https://github.com/aihe-2020/kata-objects-and-arrays' },
        { id: 54, repo_name: 'react-minimal', repo_link: 'https://github.com/aihe-2020/react-minimal' },
        { id: 55, repo_name: 'enspiraled', repo_link: 'https://github.com/aihe-2020/enspiraled' },
        { id: 56, repo_name: 'heroku-checklist', repo_link: 'https://github.com/aihe-2020/heroku-checklist' },
        { id: 57, repo_name: 'web-api-stories', repo_link: 'https://github.com/aihe-2020/web-api-stories' }
      ])
    })
}
